healthcareprofessionals/app/blueprints/organisations/__init__.py
from app.blueprints.organisations import errors  # noqa
from app.blueprints.organisations.views import organisations  # noqa

healthcareprofessionals/app/blueprints/organisations/views.py
from flask import Blueprint, render_template, abort, flash, redirect, request
from flask_login import current_user, login_required

from app.decorators import admin_required
from app.email import send_email
from .forms import *

organisations = Blueprint('organisations', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@organisations.route('/home')
@login_required
def org_home():
    orgs = current_user.organisations + Organisation.query.join(OrgStaff, Organisation.id == OrgStaff.org_id). \
        filter(OrgStaff.user_id == current_user.id).all()
    return render_template('organisations/org_dashboard.html', orgs=orgs)


@organisations.route('/org/<org_id>')
@login_required
def select_org(org_id):
    org = Organisation.query.filter_by(id=org_id).first_or_404()
    print(current_user.id, org.user_id)
    if current_user.id != org.user_id and current_user not in org.get_staff():
        abort(404)
    return render_template('organisations/org_operations.html', op='home', org=org)


@organisations.route('/add/new/', methods=['GET', 'POST'])
@login_required
def create_org():
    form = OrganisationForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = images.save(request.files['logo'])
            image_url = images.url(image_filename)
            org = Organisation(
                user_id=current_user.id,
                image_filename=image_filename,
                image_url=image_url,
                org_name=form.org_name.data,
                org_industry=form.org_industry.data,
                org_website=form.org_website.data,
                org_city=form.org_city.data,
                org_state=form.org_state.data,
                org_country=form.org_country.data,
                org_description=form.org_description.data
            )
            db.session.add(org)
            db.session.commit()
            flash('Data added!', 'success')
            logo = Organisation.query.filter(Organisation.logos).first()
            if logo is None:
                return redirect(url_for('organisations.logo_upload'))
            return redirect(url_for('organisations.org_home'))
        else:
            flash('Error! Data was not added.', 'error')
    return render_template('organisations/create_org.html', form=form)


@organisations.route('/<int:org_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_org(org_id):
    org = Organisation.query.filter(Organisation.user == current_user).filter_by(id=org_id).first_or_404()
    form = OrganisationForm(obj=org)
    if request.method == 'POST':
        if form.validate_on_submit():
            org.org_name = form.org_name.data,
            org.org_industry = form.org_industry.data,
            org.org_website = form.org_website.data,
            org.org_city = form.org_city.data,
            org.org_state = form.org_state.data,
            org.org_country = form.org_country.data,
            org.org_description = form.org_description.data
            if request.files['logo']:
                image_filename = images.save(request.files['logo'])
                image_url = images.url(image_filename)
                org.image_filename = image_filename
                org.image_url = image_url
            db.session.add(org)
            db.session.commit()
            flash('Data edited!', 'success')
            return redirect(url_for('organisations.org_home'))
        else:
            flash('Error! Data was not added.', 'error')
    return render_template('organisations/edit_org.html', form=form, org=org)


@organisations.route('/<org_id>/list_positions', methods=['Get', 'POST'])
@login_required
def list_positions(org_id):
    org = Organisation.query.filter_by(id=org_id).first_or_404()
    if current_user.id != org.user_id and current_user not in org.get_staff():
        abort(404)
    positions = Job.query.filter_by(organisation_id=org_id).all()
    return render_template('organisations/list_positions.html', positions=positions, org=org)


@organisations.route('/<org_id>/list_promos', methods=['Get', 'POST'])
@login_required
def list_promos(org_id):
    org = Organisation.query.filter_by(id=org_id).first_or_404()
    if current_user.id != org.user_id and current_user not in org.get_staff():
        abort(404)
    promos = Promo.query.filter_by(organisation_id=org_id).all()
    return render_template('organisations/list_promos.html', promos=promos, org=org)


@organisations.route('/<org_id>/list_staff', methods=['Get', 'POST'])
@login_required
def list_staff(org_id):
    org = Organisation.query.filter_by(id=org_id).first_or_404()
    if current_user.id != org.user_id and current_user not in org.get_staff():
        abort(404)
    staff = org.get_staff()
    return render_template('organisations/list_staff.html', staff=staff, org=org)


@organisations.route('/<org_id>/create/position', methods=['Get', 'POST'])
@login_required
def create_position(org_id):
    org = Organisation.query.filter_by(user_id=current_user.id).filter_by(id=org_id).first_or_404()
    form = PositionForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = None
            if request.files['logo']:
                image_filename = images.save(request.files['logo'])
            appt = Job(position_title=form.position_title.data,
                       creator_id=current_user.id,
                       image_filename=image_filename,
                       organisation_id=org_id,
                       position_city=form.position_city.data,
                       position_state=form.position_state.data,
                       position_country=form.position_country.data,
                       description=form.description.data,
                       end_date=form.end_date.data.strftime('%d %B, %Y'),  # ''' ##('%Y-%m-%d') Alternative '''
                       required_skill_one=form.required_skill_one.data,
                       required_skill_two=form.required_skill_two.data,
                       required_skill_three=form.required_skill_three.data,
                       required_skill_four=form.required_skill_four.data,
                       required_skill_five=form.required_skill_five.data,
                       required_skill_six=form.required_skill_six.data,
                       required_skill_seven=form.required_skill_seven.data,
                       required_skill_eight=form.required_skill_eight.data,
                       required_skill_nine=form.required_skill_nine.data,
                       required_skill_ten=form.required_skill_ten.data
                       )
            db.session.add(appt)
            db.session.commit()
            for u in appt.get_same_state_users():
                if appt.creator != u:
                    u.add_notification('new_job', {'job': appt.id}, related_id=current_user.id, permanent=True)
            flash('Vacancy added!', 'success')
            return redirect(url_for('jobs.job_details', position_id=appt.id, position_title=appt.position_title,
                                    position_city=appt.position_city, position_state=appt.position_state,
                                    position_country=appt.position_country))
        else:

            flash('ERROR! Position was not added.', 'error')
    return render_template('organisations/create_job.html', form=form, org=org)


@organisations.route('/<org_id>/create/promo', methods=['Get', 'POST'])
@login_required
def create_promo(org_id):
    org = Organisation.query.filter_by(user_id=current_user.id).filter_by(id=org_id).first_or_404()
    form = PromoForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = None
            if request.files['logo']:
                image_filename = images.save(request.files['logo'])
            appt = Promo(promo_title=form.promo_title.data,
                       creator_id=current_user.id,
                       image_filename=image_filename,
                       organisation_id=org_id,
                       promo_city=form.promo_city.data,
                       promo_state=form.promo_state.data,
                       promo_country=form.promo_country.data,
                       description=form.description.data,
                       end_date=form.end_date.data.strftime('%d %B, %Y'),  # ''' ##('%Y-%m-%d') Alternative '''
                       requirement_one=form.requirement_one.data,
                       requirement_two=form.requirement_two.data,
                       requirement_three=form.requirement_three.data,
                       requirement_four=form.requirement_four.data,
                       requirement_five=form.requirement_five.data,
                       requirement_six=form.requirement_six.data,
                       requirement_seven=form.requirement_seven.data,
                       requirement_eight=form.requirement_eight.data,
                       requirement_nine=form.requirement_nine.data,
                       requirement_ten=form.requirement_ten.data
                       )
            db.session.add(appt)
            db.session.commit()
            flash('Vacancy added!', 'success')
            return redirect(url_for('promos.promo_details', promo_id=appt.id, promo_title=appt.promo_title,
                                    promo_city=appt.promo_city, promo_state=appt.promo_state,
                                    promo_country=appt.promo_country))
        else:

            flash('ERROR! Promo was not added.', 'error')
    return render_template('organisations/create_promo.html', form=form, org=org)


@organisations.route('/org/<org_id>/view/')
def org_view(org_id):
    """Provide HTML page with all details on an organisation profile """
    org_detail = None
    try:

healthcareprofessionals/app/templates/organisations/create_job.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
                <a class="ui basic compact button" href="{{ url_for('organisations.list_positions', org_id=org.id) }}">
                <i class="caret left icon"></i>
                Back to "{{ org.org_name }}" Jobs' List
            </a>
            <h2 class="ui header">
                Create a new vacancy
                <div class="sub header">Set up your account</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="field">
                {{ f.render_form_field(form.position_title) }}
            </div>
            <div class="three fields">
                {{ f.render_form_field(form.position_city) }}
                {{ f.render_form_field(form.position_state) }}
                {{ f.render_form_field(form.position_country) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.end_date) }}
                {{ f.render_form_field(form.logo) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_one) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_two) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_three) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_four) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_five) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_six) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_seven) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_eight) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_nine) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.required_skill_ten) }}
            </div>

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/create_promo.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
                <a class="ui basic compact button" href="{{ url_for('organisations.list_promos', org_id=org.id) }}">
                <i class="caret left icon"></i>
                Back to "{{ org.org_name }}" Promos' List
            </a>
            <h2 class="ui header">
                Create a new vacancy
                <div class="sub header">Set up your account</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="field">
                {{ f.render_form_field(form.promo_title) }}
            </div>
            <div class="three fields">
                {{ f.render_form_field(form.promo_city) }}
                {{ f.render_form_field(form.promo_state) }}
                {{ f.render_form_field(form.promo_country) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.end_date) }}
                {{ f.render_form_field(form.logo) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_one) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_two) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_three) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_four) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_five) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_six) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_seven) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_eight) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_nine) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.requirement_ten) }}
            </div>

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/edit_org.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('organisations.select_org', org_id=org.id) }}">
                <i class="caret left icon"></i>
                Back to "{{ org.org_name }}"
            </a>
            <h2 class="ui header">
                Edit your Organization
                <span class="sub header">Set up an account</span>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="two fields">
                {{ f.render_form_field(form.org_name) }}
                {{ f.render_form_field(form.org_industry) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.logo) }}
                <div class="field">
                    <img height="100" src="{{ org.get_photo() }}">
                </div>
            </div>
            <div class="four fields">
                {{ f.render_form_field(form.org_website) }}
                {{ f.render_form_field(form.org_city) }}
                {{ f.render_form_field(form.org_state) }}
                {{ f.render_form_field(form.org_country) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.org_description) }}
            </div>


            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/list_positions.html
{% extends 'layouts/base.html' %}
{% import 'macros/job_macros.html' as job_wid %}

{% block content %}
    <div class="ui grid">
        <div class="ui stackable grid container">
            <div class="sixteen wide column">
                <a class="ui basic compact button" href="{{ url_for('organisations.select_org', org_id=org.id) }}">
                    <i class="caret left icon"></i>
                    Back to "{{ org.org_name }}"
                </a>
                <div class="ui header">
                    <h2>Organisation Dashboard : {{ org.org_name }}
                        <div class="sub header">list of organisation's positions</div>
                    </h2>
                </div>
                <div class="ui header" style="width: 100%; height: 50px">
                    <a class="ui green right floated button" href="{{ url_for('organisations.create_position', org_id=org.id) }}">Create New Job Advert</a>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="ui cards">
                    {% for job in positions %}
                        {{ job_wid.job_wid(job) }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/list_promos.html
{% extends 'layouts/base.html' %}
{% import 'macros/promo_macros.html' as promo_wid %}

{% block content %}
    <div class="ui grid">
        <div class="ui stackable grid container">
            <div class="sixteen wide column">
                <a class="ui basic compact button" href="{{ url_for('organisations.select_org', org_id=org.id) }}">
                    <i class="caret left icon"></i>
                    Back to "{{ org.org_name }}"
                </a>
                <div class="ui header">
                    <h2>Organisation Dashboard : {{ org.org_name }}
                        <div class="sub header">list of organisation's promos</div>
                    </h2>
                </div>
                <div class="ui header" style="width: 100%; height: 50px">
                    <a class="ui green right floated button" href="{{ url_for('organisations.create_promo', org_id=org.id) }}">Create New Promotion Ad</a>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="ui cards">
                    {% for promo in promos %}
                        {{ promo_wid.promo_wid(promo) }}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/list_staff.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="ui grid">
        <div class="ui stackable grid container">
            <div class="sixteen wide column">
                <a class="ui basic compact button" href="{{ url_for('organisations.select_org', org_id=org.id) }}">
                    <i class="caret left icon"></i>
                    Back to "{{ org.org_name }}"
                </a>
                <div class="ui header">
                    <h2>Organisation Dashboard : {{ org.org_name }}
                        <div class="sub header">list of organisation's staff</div>
                    </h2>
                </div>
                <div class="ui header" style="width: 100%; height: 50px">
                    <a class="ui green right floated button" href="{{ url_for('organisations.invite_user', org_id=org.id) }}">Invite Staff</a>
                </div>
            </div>
            <div class="sixteen wide column">
                <div class="column">
                    <div class="ui cards">
                        {% for user in staff %}
                            <div class="card">
                                <div class="content">
                                    <img class="right floated mini ui image" src="{{ user.get_photo() }}">
                                    <div class="header">
                                        <a href="{{ url_for('main.user', id=user.id, full_name=user.full_name) }}">{{ user.full_name }}</a>
                                    </div>
                                    <div class="meta">
                                        {{ user.profession }}, {{ user.state }}, {{ user.country }}
                                    </div>
                                    <div class="description">

                                    </div>
                                    <div class="extra content">
                                        {% if user == current_user %}

                                        {% elif not current_user.is_following(user) %}
                                            <div class="ui bottom attached button"><a
                                                    href="{{ url_for('main.follow', id=user.id, full_name=user.full_name) }}">
                                                <i class="add icon"></i> Follow</a>
                                            </div>
                                        {% else %}
                                            <div class="ui bottom attached button"><a
                                                    href="{{ url_for('main.unfollow', id=user.id, full_name=user.full_name) }}">
                                                <i class="add icon"></i> UnFollow</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="column"></div>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/new_user.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('organisations.list_staff', org_id=org.id) }}">
                <i class="caret left icon"></i>
                Back to "{{ org.org_name }}" Staff List
            </a>
            <h2 class="ui header">
                Add Staff
                <div class="sub header">Send an invite to your staff.</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="two fields">
                {{ f.render_form_field(form.first_name) }}
                {{ f.render_form_field(form.last_name) }}
            </div>

            {{ f.render_form_field(form.email) }}

            {% if form.password %}

                <div class="two fields">
                    {{ f.render_form_field(form.password) }}
                    {{ f.render_form_field(form.password2) }}
                </div>

            {% endif %}

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}
            {% if form.password %}
                {{ check.password_check('password', 0) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

healthcareprofessionals/app/templates/organisations/org_operations.html
{% extends 'layouts/base.html' %}

{% macro dashboard_option(org, title, endpoint, description=None, icon=None) %}
    <a class="column" href="{{ url_for(endpoint, org_id=org.id) }}">
        <div class="ui padded segment">
            <h3 class="ui header">
                {% if icon is not none %}
                    <i class="{{ icon }}"></i>
                {% endif %}
                <div class="content">
                    {{ title }}
                    {% if description is not none %}
                        <div class="sub header">
                            {{ description }}
                        </div>
                    {% endif %}
                </div>
            </h3>
        </div>
    </a>
{% endmacro %}

{% macro org_info(org) %}
    <table class="ui compact definition table">
        <tr>
            <td>Name</td>
            <td>{{ org.org_name }}</td>
        </tr>
        <tr>
            <td>Default Logo</td>
            <td><img height="200" src="{{ org.get_photo() }}"></td>
        </tr>
        <tr>
            <td>Creator</td>
            <td>{{ org.user.full_name }}</td>
        </tr>
        <tr>
            <td>City</td>
            <td>{{ org.org_city }}</td>
        </tr>
        <tr>
            <td>State</td>
            <td>{{ org.org_country }}</td>
        </tr>
        <tr>
            <td>Country</td>
            <td>{{ org.name }}</td>
        </tr>
        <tr>
            <td>Website</td>
            <td>{{ org.org_website }}</td>
        </tr>
        <tr>
            <td>Industry</td>
            <td>{{ org.org_industry }}</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>{{ org.org_description }}</td>
        </tr>
        <tr>
            <td>Created</td>
            <td>{{ org.created_at }}</td>
        </tr>

    </table>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('organisations.org_home') }}">
                <i class="caret left icon"></i>
                Back to Organizations List
            </a>
            <h2 class="ui header">
                Organization Dashboard : {{ org.org_name }}
                <span class="right floated ui">
                    <a href="{{ url_for('organisations.edit_org', org_id=org.id )}}">
                        <i class="icon edit"></i>
                    </a>
                </span>
            </h2>
            {{ org_info(org) }}
            <div class="ui two column stackable grid">
                {{ dashboard_option(org, 'job adverts', 'organisations.list_positions',
                                    description='Adverts created are viewable by all members within the network and outside.', icon='write square icon') }}
                {{ dashboard_option(org, 'Your Staff', 'organisations.list_staff',
                                    description='Send invites to your staffs to create their own accounts', icon='add user icon') }}
            </div>
        </div>
    </div>
{% endblock %}