healthcareprofessionals/app/blueprints/blog/__init__.py
from app.blueprints.blog.views import blog  # noqa

healthcareprofessionals/app/blueprints/blog/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user
from validate_email import validate_email

from app.models import BlogPost, BlogCategory, BlogTag, BlogComment, db, BlogNewsLetter
from app.utils import redirect_url

blog = Blueprint('blog', __name__)


@blog.route("/<int:page>", methods=['GET'])
@blog.route("/", defaults={'page': 1}, methods=['GET'])
def index(page):
    posts = BlogPost.query.order_by(BlogPost.created_at.desc()).paginate(page, per_page=10)
    categories = BlogCategory.query.order_by(BlogCategory.is_featured.desc()).order_by(BlogCategory.order.desc()).limit(10).all()
    tags = BlogTag.query.order_by(BlogTag.created_at.desc()).limit(10).all()
    return render_template("blog/index.html", posts=posts, categories=categories, tags=tags)


@blog.route('/categories/<int:page>', methods=['GET'])
@blog.route('/categories', defaults={'page': 1}, methods=['GET'])
def blog_categories(page):
    categories = BlogCategory.query.order_by(BlogCategory.is_featured.desc()).order_by(BlogCategory.order.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/index.html", categories=categories)


@blog.route('/category/<int:category_id>/<int:page>', methods=['GET'])
@blog.route('/category/<int:category_id>', defaults={'page': 1}, methods=['GET'])
def blog_category(category_id, page):
    category = BlogCategory.query.get_or_404(category_id)
    posts = BlogPost.query.filter(BlogPost.categories.any(id=category.id)).order_by(BlogPost.created_at.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/category.html", posts=posts, category=category)


@blog.route('/tag/<int:tag_id>/<int:page>', methods=['GET'])
@blog.route('/tag/<int:tag_id>', defaults={'page': 1}, methods=['GET'])
def blog_tag(tag_id, page):
    tag = BlogTag.query.get_or_404(tag_id)
    posts = BlogPost.query.filter(BlogPost.tags.any(id=tag.id)).order_by(BlogPost.created_at.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/tag.html", posts=posts, tag=tag)


@blog.route('/article/<int:article_id>', methods=['GET'])
def blog_article(article_id):
    post = BlogPost.query.get_or_404(article_id)
    categories = post.categories
    tags = post.tags
    return render_template("blog/article.html", post=post, tags=tags, categories=categories)


@blog.route('/article/<int:article_id>/comment', methods=['POST'])
def add_comment(article_id):
    post = BlogPost.query.get_or_404(article_id)
    text = request.form['text']
    if not text:
        flash("Please insert comment text", 'danger')
        return redirect(url_for('blog.blog_article', article_id=article_id))
    parent_id = request.form['parent_id']
    if parent_id and parent_id != '0' and parent_id != 0:
        comment = BlogComment(
            post_id=post.id,
            text=text,
            user_id=current_user.id,
            parent_id=parent_id
        )
    else:
        comment = BlogComment(
            post_id=post.id,
            text=text,
            user_id=current_user.id,
        )
    db.session.add(comment)
    db.session.commit()
    flash("Comment added successfully", 'success')
    return redirect(url_for('blog.blog_article', article_id=article_id))


@blog.route('/sub', methods=['POST'])
def subscribe():
    email = request.form['email']
    if not email or not validate_email(email, check_mx=False):
        flash("Please enter a valid email", 'danger')
        return redirect(redirect_url())
    if BlogNewsLetter.query.filter_by(email=email).first():
        flash("You are already subscribed", 'danger')
        return redirect(redirect_url())

    sub = BlogNewsLetter(
        email=email,
    )
    db.session.add(sub)
    db.session.commit()
    flash('Subscription {} successfully added'.format(sub.email), 'success')
    return redirect(redirect_url())

healthcareprofessionals/app/blueprints/main/views.py
import operator

from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_ckeditor import upload_success
from flask_login import current_user, login_required
from flask_sqlalchemy import Pagination
from sqlalchemy import desc, func
from app.email import send_email
from .forms import *
from ...utils import Struct

main = Blueprint('main', __name__)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route('/home')
@login_required
def index():
    check_org_exist = db.session.query(Organisation).filter_by(user_id=current_user.id).first()
    return render_template('main/user_dashboard.html', check_org_exist=check_org_exist)


@main.route('/search')
@login_required
def search():
    query = request.args.get('query')
    page = request.args.get('page')
    search_type = request.args.get('type')
    sort_by = request.args.get('sort_by')
    sort_dir = request.args.get('sort_dir')

    query = query if query is not None else ''
    page = page if page is not None else 1
    try:
        page = int(page)
    except:
        page = 1
    search_type = search_type if search_type is not None else ''
    sort_by = sort_by if sort_by is not None else ''
    sort_dir = sort_dir if sort_dir is not None else ''
    if len(query) < 3:
        flash("Search Query must be at least 3 characters", "error")
        return render_template("main/search_results.html", query=query, search_type=search_type, sort_by=sort_by,
                               sort_dir=sort_dir, results=[])
    results = []
    if search_type == '':
        job_results = Job.query.whooshee_search(query, order_by_relevance=0).all()
        user_results = User.query.whooshee_search(query, order_by_relevance=0).all()
        questions_results = Question.query.whooshee_search(query, order_by_relevance=0).all()
        products_results = MProduct.query.whooshee_search(query, order_by_relevance=0).all()

        job_results_count = Job.query.whooshee_search(query, order_by_relevance=0).count()
        user_results_count = User.query.whooshee_search(query, order_by_relevance=0).count()
        questions_results_count = Question.query.whooshee_search(query, order_by_relevance=0).count()
        products_results_count = MProduct.query.whooshee_search(query, order_by_relevance=0).count()

        all_results = job_results + user_results + questions_results + products_results
        all_count = job_results_count + user_results_count + questions_results_count + products_results_count
        results = sorted(all_results, key=operator.attrgetter("score"))
        results.reverse()
        results = results[(page-1)*40:page*40]
        paginator = Pagination(items=results, page=page, per_page=40, query=None, total=all_count)
        results = paginator

    elif search_type == 'people':
        results = User.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(user_results, key=operator.attrgetter("score"))
    elif search_type == 'jobs':
        results = Job.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(job_results, key=operator.attrgetter("score"))
    elif search_type == 'questions':
        results = Question.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(questions_results, key=operator.attrgetter("score"))
    elif search_type == 'products':
        results = MProduct.query.whooshee_search(query, order_by_relevance=10).paginate(page, per_page=10)
        # results = sorted(products_results, key=operator.attrgetter("score"))

    return render_template("main/search_results.html", query=query, search_type=search_type, sort_by=sort_by,
                           sort_dir=sort_dir, results=results)


@main.route('/feed')
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('public.index'))
    ''' this is where users will see their feeds'''
    return render_template('main/user_feed.html')


@main.route('/profile', methods=['GET', 'POST'])
def profile():
    return redirect(url_for('account.profile'))


@main.route('/list/', defaults={'page': 1})
@main.route('/list/page/<int:page>', methods=['GET'])
@login_required
def select_section(page):
    paginated = User.query.filter(User.id != current_user.id).order_by(User.id.desc()).paginate(page, per_page=25)
    return render_template('main/selection.html', paginated=paginated)


@main.route('/members/', defaults={'page': 1})
@main.route('/members/page/<int:page>', methods=['GET'])
def members(page):
    paginated = User.query.filter(User.id != current_user.id).order_by(User.id.desc()).paginate(page, per_page=25)
    return render_template('main/members.html', paginated=paginated)


## if you change profile to user on the routes it will share posts and other details.
##I made this change from user to profile so as to get the profile name to be on the url
@main.route('/profile/<int:user_id>/<full_name>', methods=['GET'], defaults={'active': 'posts', 'page': 1})
@main.route('/profile/<int:user_id>/<full_name>/<active>', methods=['GET'], defaults={'page': 1})
@main.route('/profile/<int:user_id>/<full_name>/<active>/page/<page>', methods=['GET'])

def user_detail(user_id, full_name, active, page):
    """Provide HTML page with all details on a given user """
    #user = db.session.query(User).filter(User.id == user_id, User.full_name == full_name).first_or_404()
    user = User.query.get_or_404(user_id)
    if active == 'posts':
        items = user.posts.paginate(page, per_page=10)
    elif active == 'questions':
        items = user.questions.paginate(page, per_page=10)
    else:
        items = []
    user_id = Photo.user_id
    photo = Photo.query.filter_by(id=user_id).limit(1).all()
    return render_template('public/profile.html', user=user, current_user=current_user, photo=photo, id=User.id,
                           items=items)


@main.route('/profile/<int:id>/<full_name>', defaults={'active': 'posts', 'page': 1})
@main.route('/profile/<int:id>/<full_name>/<active>', defaults={'page': 1})
@main.route('/profile/<int:id>/<full_name>/<active>/page/<int:page>')
@login_required
def user(id, full_name, active, page):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    edit_form = PostForm()
    if user == current_user:
        return redirect(url_for('main.profile', active=active))
    if active == 'posts':
        items = user.posts.paginate(page, per_page=10)
    elif active == 'questions':
        items = user.questions.paginate(page, per_page=10)
    else:
        items = []
    return render_template('main/profile.html', user=user, active=active, items=items,
                           edit_form=edit_form)  # , photo=photo)

@main.route('/public profile/<int:profile_id>/<full_name>')
def public_profile(profile_id, full_name):
    """Provide HTML page with all details on a given user """
    #user = User.query.get_or_404(user_id)
    profile_instance = Profile.query.filter_by(id=profile_id, full_name=full_name).first()
    #user = db.session.query(User).filter_by(full_name=full_name).first()
    return render_template("employer/profile_view.html", profile=profile_instance)

@main.route('/public-profile/<int:user_id>/<full_name>')
def public_user_profile(user_id, full_name):
    """Provide HTML page with all details on a given user """
    #user = User.query.get_or_404(user_id)
    profile_instance = Profile.query.filter_by(user_id=user_id, full_name=full_name).first()
    if not profile_instance:
        return redirect(url_for('main.select_section'))
    #user = db.session.query(User).filter_by(full_name=full_name).first()
    return render_template("employer/profile_view.html", profile=profile_instance)


@main.route('/<int:id>/follow/<full_name>')
@login_required
def follow(id, full_name):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    if user is None:
        flash('User {} not found.'.format(full_name))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', id=id, full_name=full_name))
    current_user.follow(user)
    db.session.commit()
    n = user.add_notification('new_follower', {"count": current_user.new_followers() + 1}, related_id=current_user.id,
                              permanent=True)
    flash('You are following {}!'.format(full_name))
    return redirect(url_for('main.user', id=id, full_name=full_name))


@main.route('/<int:id>/unfollow/<full_name>')
@login_required
def unfollow(id, full_name):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    if user is None:
        flash('User {} not found.'.format(full_name))
        return redirect(url_for(main.index))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', id=id, full_name=full_name))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}!'.format(full_name))
    return redirect(url_for('main.user', id=id, full_name=full_name))


@main.route("/<user_id>/followers", methods=['GET'], defaults={'page': 1})
@main.route("/<user_id>/followers/<int:page>", methods=['GET'])
@login_required
def followers(user_id, page):
    user_instance = User.query.get(user_id)
    if user_instance == current_user:
        title = "My Followers"
    else:
        title = "{} Followers".format(user_instance.full_name)
    followers_users = user_instance.followers.paginate(page, per_page=10)
    return render_template('main/selection.html', paginated=followers_users, user_id=user_id, title=title)

healthcareprofessionals/app/templates/blog/_flashes.html
{% macro render_flashes(class) %}
    {% with msgs = get_flashed_messages(category_filter=[class]) %}
        {% for msg in msgs %}
            <div class="alert alert-{{ class }}">
                {{ msg | safe }}
            </div>
        {% endfor %}
    {% endwith %}
{% endmacro %}

<div class="container">
    <div class="flashes">
        <br>
        {{ render_flashes('danger') }}
        {{ render_flashes('warning') }}
        {{ render_flashes('success') }}
        {{ render_flashes('primary') }}
        {{ render_flashes('secondary') }}
        {{ render_flashes('light') }}
        {{ render_flashes('dark') }}
    </div>
</div>

healthcareprofessionals/app/templates/blog/_macros.html
{% macro traverse(children, post_id, current_user) -%}
    {% if children|length > 0 %}
        {% for child in children %}
            <div class="comment-list">
                <div class="single-comment justify-content-between d-flex" style="width: 100%">
                    <div class="user justify-content-between d-flex" style="width: 100%">
                        <div class="thumb">
                            <img src="{{ child['node'].author.get_photo() }}" alt="">
                        </div>
                        <div class="desc" style="width: 100%">
                            <p class="comment">
                                {{ child['node'].text }}
                            </p>
                            <div class="d-flex justify-content-between">
                                <div class="d-flex align-items-center">
                                    <h5>
                                        <a href="{{ url_for('main.user_detail', user_id=child['node'].author.id) }}">{{ child['node'].author.full_name }}</a>
                                    </h5>
                                    <p class="date">{{ child['node'].created_at.ctime() }} </p>
                                </div>
                                {% if current_user.is_authenticated %}
                                    <div class="reply-btn">
                                        <a href="#" onclick="console.log($(this).parent());$(this).parent().parent().next('.reply-form').toggle();return false;" class="btn-reply text-uppercase">reply</a>
                                    </div>
                                {% else %}
                                    <div class="reply-btn">
                                        <a class="btn-reply text-uppercase" href="{{ url_for('account.login', next=url_for(request.endpoint, article_id=post_id, _external=True)) }}">Login To Reply</a>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="reply-form" style="display: none">
                                <div class="">
                                    <form class="form-contact comment_form" action="{{ url_for('blog.add_comment', article_id=post_id) }}"  method="POST">
                                        <input type="hidden" name="post_id" value="{{ post_id }}">
                                        <input type="hidden" name="parent_id" value="{{ child['node'].id }}">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                        <div class="row">
                                            <div class="col-12">
                                                <div class="form-group">
                                                    <input class="form-control w-100" name="text" id="comment" placeholder="Write Comment, Enter to send">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {% if 'children' in child['node'].drilldown_tree()[0].keys() %}
                                <br>
                                {{ traverse(child['node'].drilldown_tree()[0]['children'], post_id, current_user) }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endmacro %}

healthcareprofessionals/app/templates/blog/article.html
{% extends 'blog/layouts/base.html' %}
{% import 'blog/_macros.html' as macros %}
{% block extra_link %}
    <a href="#">{{ post.title[:50] }}</a>
{% endblock %}
{% block content %}
    <section class="blog_area single-post-area area-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post">
                        <div class="feature-img">
                            <img class="img-fluid" src="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=post.image, _external=True) }}" alt="">
                        </div>
                        <div class="blog_details">
                            <h2>{{ post.title }}</h2>
                            <ul class="blog-info-link mt-3 mb-4">
                                <li><a href="{{ url_for('main.user_detail', user_id=post.creator.id) }}"><i class="far fa-user"></i> {{ post.creator.full_name }}</a></li>
                                <li><a href="#"><i class="far fa-comments"></i> {{ post.comments.count() }} comments</a></li>
                            </ul>
                            <div>
                                {{ post.text | safe }}
                            </div>
                        </div>
                    </div>
                    <div class="navigation-top">
                        <div class="d-sm-flex justify-content-between text-center">
                            <div class="col-sm-4 text-center my-2 my-sm-0">
                                <p class="comment-count"><span class="align-middle"><i class="far fa-comment"></i></span>
                                    {{ post.comments.count() }} Comments</p>
                            </div>
                            <ul class="social-icons">
                                <li><a target="_blank" href="https://www.facebook.com/medivillenetwork"><i class="fab fa-facebook-f"></i></a></li>
                                <li><a target="_blank" href="https://www.instagram.com/medivillenetwork"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="comments-area" style="margin-top: 0">
                        <h4>Comments</h4>
                        {% if post.comments.count() > 0 %}
                            {% for comment in post.comments.all() %}
                                {% if comment.parent_id == None and comment.author %}
                                    <div class="comment-list">
                                        <div class="single-comment justify-content-between d-flex" style="width: 100%">
                                            <div class="user justify-content-between d-flex" style="width: 100%">
                                                <div class="thumb">
                                                    <img src="{{ comment.author.get_photo() }}" alt="">
                                                </div>
                                                <div class="desc" style="width: 100%">
                                                    <p class="comment">
                                                        {{ comment.text }}
                                                    </p>
                                                    <div class="d-flex justify-content-between">
                                                        <div class="d-flex align-items-center">
                                                            <h5>
                                                                <a href="{{ url_for('main.user_detail', user_id=comment.author.id) }}">{{ comment.author.full_name }}</a>
                                                            </h5>
                                                            <p class="date">{{ comment.created_at.ctime() }} </p>
                                                        </div>
                                                        {% if current_user.is_authenticated %}
                                                            <div class="reply-btn">
                                                                <a href="#" onclick="console.log($(this).parent());$(this).parent().parent().next('.reply-form').toggle();return false;" class="btn-reply text-uppercase">reply</a>
                                                            </div>
                                                        {% else %}
                                                            <div class="reply-btn">
                                                                <a class="btn-reply text-uppercase" href="{{ url_for('account.login', next=url_for(request.endpoint, article_id=post.id, _external=True)) }}">Login To Reply</a>
                                                            </div>
                                                        {% endif %}
                                                    </div>
                                                    <div class="reply-form" style="display: none">
                                                        <div class="">
                                                            <form class="form-contact comment_form" action="{{ url_for('blog.add_comment', article_id=post.id) }}"  method="POST">
                                                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                                                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                                                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                                                <div class="row">
                                                                    <div class="col-12">
                                                                        <div class="form-group">
                                                                            <input class="form-control w-100" name="text" id="comment" placeholder="Write Comment, Enter to send">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </form>
                                                        </div>
                                                    </div>
                                                    {% if 'children' in comment.drilldown_tree()[0].keys() %}
                                                        <br>
                                                        {{ macros.traverse(comment.drilldown_tree()[0]['children'], post.id, current_user) }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <p>No Comments Yet</p>
                        {% endif %}
                    </div>
                    {% if current_user.is_authenticated %}
                        <div class="comment-form">
                            <h4>Leave a comment</h4>
                            <form class="form-contact comment_form" action="{{ url_for('blog.add_comment', article_id=post.id) }}" id="commentForm" method="POST">
                                <input type="hidden" name="post_id" value="{{ post.id }}">
                                <input type="hidden" name="parent_id" value="0">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <input class="form-control w-100" name="text" id="comment" placeholder="Write Comment, Enter to send">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <hr>
                        <p>Please <a href="{{ url_for('account.login', next=url_for(request.endpoint, article_id=post.id, _external=True)) }}">Login</a> So You can add comments</p>
                    {% endif %}
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
{#                        <aside class="single_sidebar_widget search_widget">#}
{#                            <form action="#">#}
{#                                <div class="form-group">#}
{#                                    <div class="input-group mb-3">#}
{#                                        <input type="text" class="form-control" placeholder="Search Keyword">#}
{#                                        <div class="input-group-append">#}
{#                                            <button class="btn" type="button"><i class="ti-search"></i></button>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <button class="button rounded-0 primary-bg text-white w-100" type="submit">Search</button>#}
{#                            </form>#}
{#                        </aside>#}
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                {% for category in categories %}
                                    <li>
                                        <a href="#" class="d-flex">
                                            <p>{{ category.name }}</p>
                                            <p>&nbsp;({{ category.posts | length }} )</p>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </aside>
                        <aside class="single_sidebar_widget tag_cloud_widget">
                            <h4 class="widget_title">Tags</h4>
                            <ul class="list">
                                {% for tag in tags %}
                                    <li>
                                        <a href="{{ url_for('blog.blog_tag', tag_id=tag.id) }}">{{ tag.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </aside>
                        <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>
                            <form action="{{ url_for('blog.subscribe') }}" method="POST">
                                <div class="form-group">
                                    <input type="hidden" value="{{ csrf_token() }}" name="csrf_token">
                                    <input type="email" class="form-control" placeholder="Enter email" name="email" required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100" type="submit">Subscribe</button>
                            </form>
                        </aside>
                    </div>
                </div>

            </div>
        </div>
    </section>
{% endblock %}