healthcareprofessionals/app/models/blog.py
from sqlalchemy_mptt import BaseNestedSets

from app.utils import db
from sqlalchemy.orm import backref


class BlogCategory(db.Model):
    __tablename__ = 'blog_categories'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(), default=None, nullable=False)
    order = db.Column(db.Integer, default=0)
    is_featured = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


class BlogTag(db.Model):
    __tablename__ = 'blog_tags'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(), default=None, nullable=False)
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


class BlogPostCategory(db.Model):
    __tablename__ = 'blog_post_categories'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    category_id = db.Column(db.Integer, db.ForeignKey('blog_categories.id', ondelete="CASCADE"))
    post_id = db.Column(db.Integer, db.ForeignKey('blog_posts.id', ondelete="CASCADE"))
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


class BlogPostTag(db.Model):
    __tablename__ = 'blog_post_tags'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    tag_id = db.Column(db.Integer, db.ForeignKey('blog_tags.id', ondelete="CASCADE"))
    post_id = db.Column(db.Integer, db.ForeignKey('blog_posts.id', ondelete="CASCADE"))
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


class BlogPost(db.Model):
    __tablename__ = 'blog_posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String())
    image = db.Column(db.String(), default=None, nullable=False)
    text = db.Column(db.Text(), default=None)
    comments = db.relationship('BlogComment', backref=backref('post'), lazy='dynamic',
                               cascade="all, delete-orphan")
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete="CASCADE"))
    creator = db.relationship('User')
    categories = db.relationship("BlogCategory", secondary='blog_post_categories',
                                 backref=backref("posts"),
                                 primaryjoin=(BlogPostCategory.post_id == id),
                                 secondaryjoin=(BlogPostCategory.category_id == BlogCategory.id))
    tags = db.relationship("BlogTag", secondary='blog_post_tags',
                                 backref=backref("posts"),
                                 primaryjoin=(BlogPostTag.post_id == id),
                                 secondaryjoin=(BlogPostTag.tag_id == BlogTag.id))

    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


class BlogComment(db.Model, BaseNestedSets):
    __tablename__ = 'blog_post_comments'
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(), default=None)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete="CASCADE"))
    post_id = db.Column(db.Integer, db.ForeignKey('blog_posts.id', ondelete="CASCADE"))
    author = db.relationship('User')
    depth = db.Column(db.Integer, default=1)
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    def __init__(self, post_id, user_id, text, parent_id=None):
        self.post_id = post_id
        self.user_id = user_id
        self.text = text
        self.parent_id = parent_id


class BlogNewsLetter(db.Model):
    __tablename__ = 'blog_news_letters'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), default=None, nullable=True, unique=True)
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

healthcareprofessionals/app/blueprints/blog/__init__.py
from app.blueprints.blog.views import blog  # noqa

healthcareprofessionals/app/blueprints/blog/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user
from validate_email import validate_email

from app.models import BlogPost, BlogCategory, BlogTag, BlogComment, db, BlogNewsLetter
from app.utils import redirect_url

blog = Blueprint('blog', __name__)


@blog.route("/<int:page>", methods=['GET'])
@blog.route("/", defaults={'page': 1}, methods=['GET'])
def index(page):
    posts = BlogPost.query.order_by(BlogPost.created_at.desc()).paginate(page, per_page=10)
    categories = BlogCategory.query.order_by(BlogCategory.is_featured.desc()).order_by(BlogCategory.order.desc()).limit(10).all()
    tags = BlogTag.query.order_by(BlogTag.created_at.desc()).limit(10).all()
    return render_template("blog/index.html", posts=posts, categories=categories, tags=tags)


@blog.route('/categories/<int:page>', methods=['GET'])
@blog.route('/categories', defaults={'page': 1}, methods=['GET'])
def blog_categories(page):
    categories = BlogCategory.query.order_by(BlogCategory.is_featured.desc()).order_by(BlogCategory.order.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/index.html", categories=categories)


@blog.route('/category/<int:category_id>/<int:page>', methods=['GET'])
@blog.route('/category/<int:category_id>', defaults={'page': 1}, methods=['GET'])
def blog_category(category_id, page):
    category = BlogCategory.query.get_or_404(category_id)
    posts = BlogPost.query.filter(BlogPost.categories.any(id=category.id)).order_by(BlogPost.created_at.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/category.html", posts=posts, category=category)


@blog.route('/tag/<int:tag_id>/<int:page>', methods=['GET'])
@blog.route('/tag/<int:tag_id>', defaults={'page': 1}, methods=['GET'])
def blog_tag(tag_id, page):
    tag = BlogTag.query.get_or_404(tag_id)
    posts = BlogPost.query.filter(BlogPost.tags.any(id=tag.id)).order_by(BlogPost.created_at.desc()).paginate(page, per_page=40)
    return render_template("blog/categories/tag.html", posts=posts, tag=tag)


@blog.route('/article/<int:article_id>', methods=['GET'])
def blog_article(article_id):
    post = BlogPost.query.get_or_404(article_id)
    categories = post.categories
    tags = post.tags
    return render_template("blog/article.html", post=post, tags=tags, categories=categories)


@blog.route('/article/<int:article_id>/comment', methods=['POST'])
def add_comment(article_id):
    post = BlogPost.query.get_or_404(article_id)
    text = request.form['text']
    if not text:
        flash("Please insert comment text", 'danger')
        return redirect(url_for('blog.blog_article', article_id=article_id))
    parent_id = request.form['parent_id']
    if parent_id and parent_id != '0' and parent_id != 0:
        comment = BlogComment(
            post_id=post.id,
            text=text,
            user_id=current_user.id,
            parent_id=parent_id
        )
    else:
        comment = BlogComment(
            post_id=post.id,
            text=text,
            user_id=current_user.id,
        )
    db.session.add(comment)
    db.session.commit()
    flash("Comment added successfully", 'success')
    return redirect(url_for('blog.blog_article', article_id=article_id))


@blog.route('/sub', methods=['POST'])
def subscribe():
    email = request.form['email']
    if not email or not validate_email(email, check_mx=False):
        flash("Please enter a valid email", 'danger')
        return redirect(redirect_url())
    if BlogNewsLetter.query.filter_by(email=email).first():
        flash("You are already subscribed", 'danger')
        return redirect(redirect_url())

    sub = BlogNewsLetter(
        email=email,
    )
    db.session.add(sub)
    db.session.commit()
    flash('Subscription {} successfully added'.format(sub.email), 'success')
    return redirect(redirect_url())

healthcareprofessionals/app/templates/blog/layouts/base.html
<!doctype html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="img/favicon.png" type="image/png">
    <title>Mediville Blog</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/themify-icons.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/flaticon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/vendors/fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/vendors/owl-carousel/owl.carousel.min.html') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/vendors/animate-css/animate.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='blog/css/responsive.css') }}">

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/ico/favicon.ico') }}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{{ url_for('static', filename='images/ico/apple-touch-icon-144-precomposed.png') }}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{{ url_for('static', filename='images/ico/apple-touch-icon-114-precomposed.png') }}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{{ url_for('static', filename='images/ico/apple-touch-icon-72-precomposed.png') }}">
    <link rel="apple-touch-icon-precomposed"
          href="{{ url_for('static', filename='images/ico/apple-touch-icon-57-precomposed.png') }}">
    <meta name="google-site-verification" content="eO7v2aO6uakHOD3gSnChM4_GSUpar3MVqPZzr9cWENE" />

    {% block custom_head_tags %}{% endblock %}

</head>
<body>
<section class="header-top">
    <div class="container">
        <div class="row align-items-center justify-content-between">
            <div class="col-6 col-lg-4">
                <div class="float-left">
                    <ul class="header_social">
                        <li><a target="_blank" href="https://www.facebook.com/medivillenetwork"><i class="ti-facebook"></i></a></li>
                        {#                        <li><a href="#"><i class="ti-twitter"></i></a></li>#}
                        <li><a target="_blank" href="https://www.instagram.com/medivillenetwork"><i class="ti-instagram"></i></a></li>
                        {#                        <li><a href="#"><i class="ti-skype"></i></a></li>#}
                        {#                        <li><a href="#"><i class="ti-vimeo"></i></a></li>#}
                    </ul>
                </div>
            </div>
            <div class="col-6 col-lg-4 col-md-6 col-sm-6 logo-wrapper">
                <a href="{{ url_for('blog.index') }}" class="logo">
                    <img src="{{ url_for('static', filename='images/logo_blog.png') }}" alt="">
                </a>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 search-trigger">
                <div class="right-button">
                    <ul>
                        <li><a href="{{ url_for('public.about') }}">About</a></li>
                        <li><a href="#footer-sub">Subscribe</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>


<header id="header" class="header_area">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                        <li class="nav-item {% if request.endpoint == 'blog.index' %} active {% endif %}"><a class="nav-link" href="{{ url_for('blog.index') }}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('blog.blog_categories') }}">Categories</a></li>
                        <li class="nav-item {% if request.endpoint == 'public.contact' %} active {% endif %}"><a class="nav-link" href="{{ url_for('public.contact') }}">Contact Us</a></li>
                        <li class="nav-item {% if request.endpoint == 'home.index' %} active {% endif %}"><a class="nav-link" href="{{ url_for('main.index') }}">Mediville Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</header>


<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content d-md-flex justify-content-between align-items-center">
                <div class="mb-3 mb-md-0">
                    <h2>Blog</h2>
                </div>
                <div class="page_link">
                    <a href="{{ url_for('main.index') }}">Home</a>
                    <a href="{{ url_for('blog.index') }}">Blog</a>
                    {% block extra_link %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</section>
{% include 'blog/_flashes.html' %}
{% block content %}{% endblock %}

<footer class="footer-area" style="border-top: 1px solid #e8edf1;">
    <div class="container">
        <div class="row">
            <div class="col-xl-4 col-lg-4 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>About Us</h4>
                <p>A healthcare professional networking and jobs platform built in collaboration with doctors, nurses and other health and allied care professionals.</p>
                <div class="footer-logo" style="text-align: center;width: 100%;">
                    <img src="{{ url_for('static', filename='images/blog_footer.png') }}" alt="">
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-sm-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>Important Link</h4>
                <ul>
                    <li><a href="{{ url_for('blog.index') }}">Blog Home</a></li>
                    <li><a href="{{ url_for('main.index') }}">Mediville Home</a></li>
                    <li><a href="{{ url_for('public.about') }}">About Us</a></li>
                    <li><a href="{{ url_for('public.contact') }}">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-xl-5 col-lg-5 col-sm-6 col-md-6 mb-4 mb-xl-0 single-footer-widget">
                <h4>Newsletter</h4>
                <p>Subscribe To receive updates for Mediville's blog new posts.</p>
                <div class="form-wrap">
                    <form  action="{{ url_for('blog.subscribe') }}" method="POST" id="footer-sub">
                        <div class="input-group">
                            <input type="hidden" value="{{ csrf_token() }}" name="csrf_token">
                            <input type="email" class="form-control" name="email" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '">
                            <div class="input-group-append">
                                <button class="btn click-btn" type="submit">
                                    <i class="fab fa-telegram-plane"></i>
                                </button>
                            </div>
                        </div>
                        <div style="position: absolute; left: -5000px;">
                            <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                        </div>
                        <div class="info"></div>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-bottom row align-items-center text-center text-lg-left no-gutters">
            <p class="footer-text m-0 col-lg-8 col-md-12">
                Copyright &copy; Mediville <script>document.write(new Date().getFullYear());</script> | All rights reserved...
            </p>
            <div class="col-lg-4 col-md-12 text-center text-lg-right footer-social">
                <a target="_blank" href="https://www.facebook.com/medivillenetwork"><i class="ti-facebook"></i></a>
                <a target="_blank" href="https://www.instagram.com/medivillenetwork"><i class="ti-instagram"></i></a>
                {#                    <a href="#"><i class="ti-twitter-alt"></i></a>#}
                {#                    <a href="#"><i class="ti-dribbble"></i></a>#}
                {#                    <a href="#"><i class="ti-linkedin"></i></a>#}
            </div>
        </div>
    </div>
</footer>



<script src="{{ url_for('static', filename='blog/js/jquery-2.2.4.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/popper.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/stellar.js') }}"></script>
<script src="{{ url_for('static', filename='blog/vendors/popup/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/jquery.ajaxchimp.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/waypoints.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/mail-script.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/contact.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/jquery.form.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/jquery.validate.min.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/mail-script.js') }}"></script>
<script src="{{ url_for('static', filename='blog/js/theme.js') }}"></script>

<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script>
    $(document).ready(function() {
        if ($('.alert').length){
            $('html, body').animate({
                scrollTop: $('.alert').offset().top - 150
            }, 1000);
        }
    })
</script>
{% block scripts %}{% endblock %}
</body>
</html>