healthcareprofessionals/app/blueprints/jobs/views.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required

from app.models import *
from datetime import datetime, timedelta, date


jobs = Blueprint('jobs', __name__)


@jobs.route('/list/')
def jobs_list():
    appts = Job.query.filter(Job.organisation != None).filter(Job.end_date >= datetime.now()).order_by(Job.pub_date.asc()).all()
    #jobs = JobPikr.query.filter(JobPikr.has_expired == "false").all()
    jobs = JobPikr.query.filter(JobPikr.company_name != None).filter(JobPikr.crawl_timestamp >= (date.today()-timedelta(days=40)).isoformat()).order_by(JobPikr.job_title.asc()).all()
    #crawlers = Crawledjob.query.filter(Crawledjob.company_name != None).filter(Crawledjob.created_at >= duration).order_by(Crawledjob.job_title.asc()).all()
    return render_template('jobs/alljobs.html', appts=appts, jobs=jobs)#crawlers=crawlers, jobs=jobs)


@jobs.route('/c/<int:job_id>/<job_title>/<job_city>/<job_state>/<job_country>')
def crawled_job_details(job_id, job_title, job_city, job_state, job_country):
    appts = Crawledjob.query.filter(Crawledjob.id == job_id).first_or_404()
    return render_template('jobs/crawled_job_details.html', appt=appts)


@jobs.route('/<int:job_id>/<job_title>/<city>/')
def jobpikr_details(job_id, job_title, city):
    appts = JobPikr.query.filter(JobPikr.job_title == job_title).first_or_404()
    return render_template('jobs/jobspikr_details.html', appt=appts)


@jobs.route('/<int:position_id>/<position_title>/<position_city>/<position_state>/<position_country>')
def job_details(position_id, position_title, position_city, position_state, position_country):
    appts = Job.query.filter(Job.id == position_id).first_or_404()
    org_users = User.query.all()
    orgs = Organisation.query.filter(Organisation.user_id == User.id).all()
    return render_template('jobs/job_details.html', appt=appts, orgs=orgs, org_users=org_users)


@jobs.route('/<int:position_id>/<position_title>/apply')
@login_required
def job_apply(position_id, position_title):
    appt = db.session.query(Job).get(position_id)
    if appt is None:
        abort(404)
    elif current_user.id is None:
        abort(403)
    else:
        if appt.creator == current_user:
            flash("You Can't Apply to {0} because you created it".format(appt.position_title), 'warning')
            return redirect(url_for('jobs.jobs_list'))
        extra = Extra.query.filter_by(user_id=current_user.id).first()
        if not extra:
            flash(
                "You can't apply to {0} because you didn't add your extra details , please go to <a href='{1}'>Profile</a> to add it".format(
                    appt.position_title, url_for('account.change_extra_details')), 'warning')
            return redirect(url_for('jobs.jobs_list'))
        applications = Application.query.filter(Application.position_id == appt.id).all()
        applicants = [appt.user_id for appt in applications]
        if current_user.id in applicants:
            flash("You have <strong>already applied</strong> for {0}.".format(appt.position_title), 'warning')
            return redirect(url_for('jobs.jobs_list'))
        else:
            appts = Application(position_id=appt.id, user_id=current_user.id)
            db.session.add(appts)
            db.session.commit()
            flash("You have successfully applied to {0}.".format(appt.position_title), 'success')
            return redirect(url_for('jobs.jobs_list'))


@jobs.route('/some-endpoint', methods=['POST'])
def share_email():
    share_text = "Your friend {0} on http://teachera.org want to recommend you this open course: {1}.\n" \
                 "Register, and view it here: {2}." \
                 "\n\n" \
                 "Regards,\n" \
                 "Teachera.org team"

    formated_text = share_text.format(current_user.name, request.form['title'], request.form['url'])
    message = Message(subject="#Write Something Here!",
                      sender='#Write Something Here!',
                      reply_to=current_user.email,
                      recipients=[request.form['email']],
                      body=formated_text)
    mail.send(message)

    print(request.__dict__)
    print(request.form)
    return jsonify(status='success')

healthcareprofessionals/app/blueprints/main/views.py
import operator

from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_ckeditor import upload_success
from flask_login import current_user, login_required
from flask_sqlalchemy import Pagination
from sqlalchemy import desc, func
from app.email import send_email
from .forms import *
from ...utils import Struct

main = Blueprint('main', __name__)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@main.route('/home')
@login_required
def index():
    check_org_exist = db.session.query(Organisation).filter_by(user_id=current_user.id).first()
    return render_template('main/user_dashboard.html', check_org_exist=check_org_exist)


@main.route('/search')
@login_required
def search():
    query = request.args.get('query')
    page = request.args.get('page')
    search_type = request.args.get('type')
    sort_by = request.args.get('sort_by')
    sort_dir = request.args.get('sort_dir')

    query = query if query is not None else ''
    page = page if page is not None else 1
    try:
        page = int(page)
    except:
        page = 1
    search_type = search_type if search_type is not None else ''
    sort_by = sort_by if sort_by is not None else ''
    sort_dir = sort_dir if sort_dir is not None else ''
    if len(query) < 3:
        flash("Search Query must be at least 3 characters", "error")
        return render_template("main/search_results.html", query=query, search_type=search_type, sort_by=sort_by,
                               sort_dir=sort_dir, results=[])
    results = []
    if search_type == '':
        job_results = Job.query.whooshee_search(query, order_by_relevance=0).all()
        user_results = User.query.whooshee_search(query, order_by_relevance=0).all()
        questions_results = Question.query.whooshee_search(query, order_by_relevance=0).all()
        products_results = MProduct.query.whooshee_search(query, order_by_relevance=0).all()

        job_results_count = Job.query.whooshee_search(query, order_by_relevance=0).count()
        user_results_count = User.query.whooshee_search(query, order_by_relevance=0).count()
        questions_results_count = Question.query.whooshee_search(query, order_by_relevance=0).count()
        products_results_count = MProduct.query.whooshee_search(query, order_by_relevance=0).count()

        all_results = job_results + user_results + questions_results + products_results
        all_count = job_results_count + user_results_count + questions_results_count + products_results_count
        results = sorted(all_results, key=operator.attrgetter("score"))
        results.reverse()
        results = results[(page-1)*40:page*40]
        paginator = Pagination(items=results, page=page, per_page=40, query=None, total=all_count)
        results = paginator

    elif search_type == 'people':
        results = User.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(user_results, key=operator.attrgetter("score"))
    elif search_type == 'jobs':
        results = Job.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(job_results, key=operator.attrgetter("score"))
    elif search_type == 'questions':
        results = Question.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
        # results = sorted(questions_results, key=operator.attrgetter("score"))
    elif search_type == 'products':
        results = MProduct.query.whooshee_search(query, order_by_relevance=10).paginate(page, per_page=10)
        # results = sorted(products_results, key=operator.attrgetter("score"))

    return render_template("main/search_results.html", query=query, search_type=search_type, sort_by=sort_by,
                           sort_dir=sort_dir, results=results)


@main.route('/feed')
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('public.index'))
    ''' this is where users will see their feeds'''
    return render_template('main/user_feed.html')


@main.route('/profile', methods=['GET', 'POST'])
def profile():
    return redirect(url_for('account.profile'))


@main.route('/list/', defaults={'page': 1})
@main.route('/list/page/<int:page>', methods=['GET'])
@login_required
def select_section(page):
    paginated = User.query.filter(User.id != current_user.id).order_by(User.id.desc()).paginate(page, per_page=25)
    return render_template('main/selection.html', paginated=paginated)


@main.route('/members/', defaults={'page': 1})
@main.route('/members/page/<int:page>', methods=['GET'])
def members(page):
    paginated = User.query.filter(User.id != current_user.id).order_by(User.id.desc()).paginate(page, per_page=25)
    return render_template('main/members.html', paginated=paginated)


## if you change profile to user on the routes it will share posts and other details.
##I made this change from user to profile so as to get the profile name to be on the url
@main.route('/profile/<int:user_id>/<full_name>', methods=['GET'], defaults={'active': 'posts', 'page': 1})
@main.route('/profile/<int:user_id>/<full_name>/<active>', methods=['GET'], defaults={'page': 1})
@main.route('/profile/<int:user_id>/<full_name>/<active>/page/<page>', methods=['GET'])

def user_detail(user_id, full_name, active, page):
    """Provide HTML page with all details on a given user """
    #user = db.session.query(User).filter(User.id == user_id, User.full_name == full_name).first_or_404()
    user = User.query.get_or_404(user_id)
    if active == 'posts':
        items = user.posts.paginate(page, per_page=10)
    elif active == 'questions':
        items = user.questions.paginate(page, per_page=10)
    else:
        items = []
    user_id = Photo.user_id
    photo = Photo.query.filter_by(id=user_id).limit(1).all()
    return render_template('public/profile.html', user=user, current_user=current_user, photo=photo, id=User.id,
                           items=items)


@main.route('/profile/<int:id>/<full_name>', defaults={'active': 'posts', 'page': 1})
@main.route('/profile/<int:id>/<full_name>/<active>', defaults={'page': 1})
@main.route('/profile/<int:id>/<full_name>/<active>/page/<int:page>')
@login_required
def user(id, full_name, active, page):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    edit_form = PostForm()
    if user == current_user:
        return redirect(url_for('main.profile', active=active))
    if active == 'posts':
        items = user.posts.paginate(page, per_page=10)
    elif active == 'questions':
        items = user.questions.paginate(page, per_page=10)
    else:
        items = []
    return render_template('main/profile.html', user=user, active=active, items=items,
                           edit_form=edit_form)  # , photo=photo)

@main.route('/public profile/<int:profile_id>/<full_name>')
def public_profile(profile_id, full_name):
    """Provide HTML page with all details on a given user """
    #user = User.query.get_or_404(user_id)
    profile_instance = Profile.query.filter_by(id=profile_id, full_name=full_name).first()
    #user = db.session.query(User).filter_by(full_name=full_name).first()
    return render_template("employer/profile_view.html", profile=profile_instance)

@main.route('/public-profile/<int:user_id>/<full_name>')
def public_user_profile(user_id, full_name):
    """Provide HTML page with all details on a given user """
    #user = User.query.get_or_404(user_id)
    profile_instance = Profile.query.filter_by(user_id=user_id, full_name=full_name).first()
    if not profile_instance:
        return redirect(url_for('main.select_section'))
    #user = db.session.query(User).filter_by(full_name=full_name).first()
    return render_template("employer/profile_view.html", profile=profile_instance)


@main.route('/<int:id>/follow/<full_name>')
@login_required
def follow(id, full_name):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    if user is None:
        flash('User {} not found.'.format(full_name))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', id=id, full_name=full_name))
    current_user.follow(user)
    db.session.commit()
    n = user.add_notification('new_follower', {"count": current_user.new_followers() + 1}, related_id=current_user.id,
                              permanent=True)
    flash('You are following {}!'.format(full_name))
    return redirect(url_for('main.user', id=id, full_name=full_name))


@main.route('/<int:id>/unfollow/<full_name>')
@login_required
def unfollow(id, full_name):
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    if user is None:
        flash('User {} not found.'.format(full_name))
        return redirect(url_for(main.index))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', id=id, full_name=full_name))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}!'.format(full_name))
    return redirect(url_for('main.user', id=id, full_name=full_name))


@main.route("/<user_id>/followers", methods=['GET'], defaults={'page': 1})
@main.route("/<user_id>/followers/<int:page>", methods=['GET'])
@login_required
def followers(user_id, page):
    user_instance = User.query.get(user_id)
    if user_instance == current_user:
        title = "My Followers"
    else:
        title = "{} Followers".format(user_instance.full_name)
    followers_users = user_instance.followers.paginate(page, per_page=10)
    return render_template('main/selection.html', paginated=followers_users, user_id=user_id, title=title)

healthcareprofessionals/app/blueprints/promos/views.py
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required

from app.models import *

promos = Blueprint('promos', __name__)


@promos.route('/list/')
def promos_list():
    #appts = Promo.query.filter(Promo.organisation != None).filter(Promo.end_date >= datetime.now()).order_by(Promo.pub_date.asc()).all()
    #return render_template('promos/allpromos.html', appts=appts)
    #def promos_list():
    appts = Promo.query.filter(Promo.organisation != None).filter(Promo.end_date >= datetime.now()).order_by(Promo.pub_date.asc()).all()
    return render_template('promos/allpromos.html', appts=appts)




@promos.route('/<int:promo_id>/<promo_title>/<promo_city>/<promo_state>/<promo_country>')
def promo_details(promo_id, promo_title, promo_city, promo_state, promo_country):
    appts = Promo.query.filter(Promo.id == promo_id).first_or_404()
    org_users = User.query.all()
    orgs = Organisation.query.filter(Organisation.user_id == User.id).all()
    return render_template('promos/promo_details.html', appt=appts, orgs=orgs, org_users=org_users)


@promos.route('/<int:promo_id>/<promo_title>/apply')
@login_required
def promo_apply(promo_id, promo_title):
    appt = db.session.query(Promo).get(promo_id)
    if appt is None:
        abort(404)
    elif current_user.id is None:
        abort(403)
    
    else:
        
        if appt.creator == current_user:
            flash("You can't apply to {0} because you created it".format(appt.promo_title), 'warning')
            return redirect(url_for('promos.promos_list'))
        extra = Extra.query.filter_by(user_id=current_user.id).first()
        if not extra:
            flash(
                "You can't participate to {0} because you didn't add your extra details , please go to <a href='{1}'>profile</a> to add it".format(
                    appt.promo_title, url_for('account.change_extra_details')), 'warning')
            return redirect(url_for('promos.promos_list'))
        submissions = Submission.query.filter(Submission.promo_id == appt.id).all()
        submissions = [appt.user_id for appt in submissions]
        if current_user.id in submissions:
            flash("You have <strong>already participated</strong> for {0}.".format(appt.promo_title), 'warning')
            return redirect(url_for('promos.promos_list'))
        else:
            appts = Submission(promo_id=appt.id, user_id=current_user.id)
            db.session.add(appts)
            db.session.commit()
            flash("You have successfully participated to {0}.".format(appt.promo_title), 'success')
            return redirect(url_for('promos.promos_list'))


@promos.route('/some-endpoint', methods=['POST'])
def share_email():
    share_text = "Your friend {0} on http://teachera.org want to recommend you this open course: {1}.\n" \
                 "Register, and view it here: {2}." \
                 "\n\n" \
                 "Regards,\n" \
                 "Teachera.org team"

    formated_text = share_text.format(current_user.name, request.form['title'], request.form['url'])
    message = Message(subject="#Write Something Here!",
                      sender='#Write Something Here!',
                      reply_to=current_user.email,
                      recipients=[request.form['email']],
                      body=formated_text)
    mail.send(message)

    print(request.__dict__)
    print(request.form)
    return jsonify(status='success')

healthcareprofessionals/app/templates/macros/allquestion_macros.html
{% import 'macros/answer_macros.html' as traverse %}
{% macro question_wid(question, corner=False) -%}
    {% if question.user %}
        <div class="ui fluid card post-card">

            <div class="extra content">
                <h2 class="left floated ui header">
                    <img class="left floated mini ui image" src="{{ question.user.get_photo() }}">
                    <a href="{{ url_for('main.user', id=question.user.id, full_name=question.user.full_name) }}">{{ question.user.full_name }}</a>
                </h2>
                <div class="meta">
                    <span class="date">{{question.user.kw_seeker_badge}}</span>
                </div>
            </div>
            <div class="content">
                <div class="header">
                    <a href="{{ url_for('main.question_details', question_id=question.id, title=question.title ) }}">{{ question.title }}</a>
                </div>
            </div>
        {% if corner %}
                <a class="ui blue left corner  label" >
                    <i class="edit icon"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
{%- endmacro %}  

healthcareprofessionals/app/templates/macros/answer_macros.html
{% macro traverse(children, question_id, moment, current_user) -%}
    {% if children|length > 0 %}
        {% for child in children %}
            <div class="comment">
                <a class="avatar" href="{{ url_for('main.user', id=child['node'].creator.id, full_name=child['node'].creator.full_name) }}">
                    <img class="rounded" src="{{ child['node'].creator.get_photo() }}">
                </a>
                <div class="content">
                    <a class="author" href="{{ url_for('main.user', id=child['node'].creator.id, full_name=child['node'].creator.full_name) }}">{{ child['node'].author }}</a>

                    {% if child['node'].creator.id == current_user.id %}
                        <p class="options btn" style="cursor: pointer; float: right;">
                            <i class="large ellipsis vertical icon right floated" style="margin-right: -0.5rem;">
                            </i>
                        </p>
                        <div class="ui special popup" style="margin-right: -1rem;margin-top: 2rem;padding-left: 1px;padding-right: 1px; padding-bottom: 1px">
                            <ul style="list-style-type: none;padding:0;margin-bottom: 1px;margin-top: 0">
                                <li class="item" style="padding: 5px 35px 3px 15px"
                                    onclick='editAnswer("{{ child['node'].id }}",  {{ child['node'].body | tojson }})'>
                                    <a href="#">Edit Answer</a>
                                </li>
                                <li class="item" style="padding: 5px 35px 3px 15px" onclick='deleteAnswer("{{ child['node'].id }}")'>
                                    <a href="#">Delete Answer</a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}

                    <div class="metadata">
                        <span class="date">{{ moment(child['node'].timestamp).fromNow() }}</span>
                    </div>
                    <div class="text">
                        {{ child['node'].body }}
                    </div>
                    <div class="actions">
                        {% if current_user.is_authenticated %}
                            <a class="reply" href="#"
                               onclick="$('#answer-'+{{ child['node'].id }}).toggleClass('display-none');return false;">Reply</a>
                            <form id="answer-{{ child['node'].id }}" class="ui reply form display-none" method="POST"
                                  action="{{ url_for('main.parent_answers') }}">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                <input type="hidden" name="question_id" value="{{ question_id }}"/>
                                <input type="hidden" name="parent_id" value="{{ child['node'].id }}"/>
                                <div class="inline fields">

                                    <div class="field" style="width: calc(100% - 60px);">
                                        <input id="replyid" name="reply" style="background: #eee;border-radius: 15px;width:100%">
                                    </div>
                                    <div class="field  "><button id="submit" name="submit" type="submit" class="ui icon primary button"><i class="icon send"></i></button></div>
                                </div>
                            </form>
                        {% endif %}
                    </div>
                </div>
                {% if 'children' in child['node'].drilldown_tree()[0].keys() %}
                    <div class="comments">
                        {{ traverse(child['node'].drilldown_tree()[0]['children'], question_id, moment, current_user) }}
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    {%- endif %}

{%- endmacro %}

healthcareprofessionals/app/templates/macros/crawled_job_macros.html
{% macro crawledjob_wid(crawledjob) -%}
    <div class="card">
        <div class="content">
            <div class="header">
                <!----<div class="center aligned ui">
                    <img height="100" src="{{ crawledjob.image_filename }}">
                </div>------>
                <!----<hr>----->
                <a href="{{ url_for('jobs.crawled_job_details', job_id=crawledjob.id, job_title=crawledjob.job_title, job_city=crawledjob.job_city, job_state=crawledjob.job_state, job_country=crawledjob.job_country) }}">{{ crawledjob.job_title }}</a>
            </div>
            <div class="meta">Published By :<span class="ui primary label">{{ crawledjob.company_name }}</span></div>
            <div class="meta">Published&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ crawledjob.pub_date }}<br>
                 {% if crawledjob.end_date  %}Ends&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;:{{ crawledjob.end_date}}{% else %}{% endif %}</div>
            <div class="description">
                {{ crawledjob.job_city }}, {{ crawledjob.job_state }}, {{ crawledjob.job_country }}
            </div>
        </div>
      </div>
{%- endmacro %}

healthcareprofessionals/app/templates/macros/job_macros.html
{% macro job_wid(job, corner=False) -%}
    <div class="card">
        <div class="content">
            <div class="header">
                <div class="center aligned ui">
                    <img height="100" src="{{ job.get_photo() }}">
                </div>
                <hr>
                <a href="{{ url_for('jobs.job_details', position_id=job.id, position_title=job.position_title, position_city=job.position_city, position_state=job.position_state, position_country=job.position_country) }}">{{ job.position_title }}</a>
            </div>
            <div class="meta">Published By :<span class="ui primary label">{{ job.organisation.org_name }}</span></div>
            <div class="meta">Published&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ job.pub_date.strftime( '%d %B, %Y ') }}<br>
                Ends&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ job.end_date.strftime( '%d %B, %Y ') }}</div>
            <div class="description">
                {{ job.position_city }}, {{ job.position_state }}, {{ job.position_country }}
            </div>
        </div>
            {% if corner %}
            <a class="ui pink left corner  label" >
                <i class="suitcase icon"></i>
            </a>
        {% endif %}
    </div>
{%- endmacro %}

healthcareprofessionals/app/templates/macros/jobpikr_macros.html
{% macro jobpikr_wid(jobpikr) -%}
    <div class="card">
        <div class="content">
            <div class="header">
                <a href="{{ url_for('jobs.jobpikr_details', job_id=jobpikr.id, job_title=jobpikr.job_title, city=jobpikr.city) }}">{{ jobpikr.job_title }}</a>
            </div>
            <div class="meta">Published By :<span class="ui primary label">{{ jobpikr.company_name }}</span></div>
            <div class="meta">Published&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ jobpikr.post_date.strftime( '%d %B, %Y ') }}<br>
                </div>
            <div class="description">
                {{ jobpikr.inferred_state }}, {{ jobpikr.inferred_country }}            
            </div>
        </div>
    </div> 
{%- endmacro %}

healthcareprofessionals/app/templates/macros/promo_macros.html
{% macro promo_wid(promo) -%}
    <div class="card">
        <div class="content">
            <div class="header">
                <div class="center aligned ui">
                    <img height="100" src="{{ promo.get_photo() }}">
                </div>
                <hr>
                <a href="{{ url_for('promos.promo_details', promo_id=promo.id, promo_title=promo.promo_title, promo_city=promo.promo_city, promo_state=promo.promo_state, promo_country=promo.promo_country) }}">{{ promo.promo_title }}</a>
            </div>
            <div class="meta">Published By :<span class="ui primary label">{{ promo.organisation.org_name }}</span></div>
            <div class="meta">Published&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ promo.pub_date.strftime( '%d %B, %Y ') }}<br>
                Ends&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ promo.end_date.strftime( '%d %B, %Y ') }}</div>
            <div class="description">
                {{ promo.promo_city }}, {{ promo.promo_state }}, {{ promo.promo_country }}
            </div>
        </div>
    </div>
{%- endmacro %}

healthcareprofessionals/app/templates/macros/question_macros.html
{% import 'macros/answer_macros.html' as traverse %}
{% macro question_wid(question, moment, current_user) -%}
    <div class="ui fluid card post-card">
                    <div class="extra content">
                        <h2 class="left floated ui header">
                            <img class="left floated mini ui image" src="{{ question.user.get_photo() }}">
							<a href="{{ url_for('main.public_profile', user_id=question.user.id, full_name=question.user.full_name) }}">{{ question.user.full_name }}</a>    
                        </h2>
			<div class="meta">
				<span class="date">{{question.user.kw_seeker_badge}}</span>
			</div>
                        {% if question.user.id == current_user.id %}
                            <p class="options btn" style="cursor: pointer">
                                <i class="large ellipsis vertical icon right floated" style="margin-right: -0.5rem;">
                                </i>
                            </p>
                            <div class="ui special popup" style="margin-right: -1rem;margin-top: 2rem;padding-left: 1px;padding-right: 1px; padding-bottom: 1px">
                                <ul style="list-style-type: none;padding:0;margin-bottom: 1px;margin-top: 0">
                                    <li class="item" style="padding: 5px 35px 3px 15px"
                                        onclick='editQuestion("{{ question.id }}", {{ question.title | tojson  }}, {{ question.description | tojson }})'>
                                        <a href="{{ url_for('main.question_details', question_id=question.id, title=question.title) }}">Edit Question</a>
                                    </li>
                                    <li class="item" style="padding: 5px 35px 3px 15px" onclick='deleteQuestion("{{ question.id }}")'>
                                        <a href="{{ url_for('main.question_details', question_id=question.id, title=question.title) }}">Delete Question</a>
                                    </li>
                                </ul>
                            </div>
                        {% endif %}

                    </div>
                    <div class="content">
                        <div class="header">
                            <a href="{{ url_for('main.question_details', question_id=question.id, title=question.title ) }}">{{ question.title }}</a>
                        </div>
                        <div class="meta">
                            <span class="right floated time">{{ moment(question.timestamp).fromNow() }}</span>
                        </div>
                    </div>
    </div>
{%- endmacro %}